server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**

            - id: resume-service
              uri: ${RESUME_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/resumes/**
            - id: job-description-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/job-descriptions/**
  data:
    redis:
      host: ${redis_host:localhost}}
      port: ${redis_port:6379}}
      username: ${redis_username}
      password: ${redis_password}

jwt:
  secret:
    key: ${jwt_secret_key}
cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE